name: TownyTweaks
version: '${project.version}'
main: me.darthpeti.townytweaks.Main
api-version: 1.18
authors: [ darthpeti, 0xbit, _kz_n]
description: Adds many features to your towny server
commands:
  townytweaks:
    permission: townytweaks.admin
    permission-message: You do not have permission to use this command.
    usage: /townytweaks <reload> or /townytweaks <set> <option> <var>
